name: 'Keep dev branch in sync with main and deploy work'

on:
  push:
    branches:
      - master

jobs:
  sync_dev_with_master:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - run: |
         gh pr create --base development --title "chore: sync dev with main" --body "Body for pr"
         gh pr list
         gh pr merge --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: devmhorn
          channelId: live
